### ISSUE TITLE
[Bug]: Chart package contains two service.yaml files

### ISSUE THREAD

**Issue by dirien** [hugoprudente/charts#47]
Hi,

the packaged chart contains, twice the `service.yaml` file. Once called: `service.yaml` and the other one `service.yaml~`. 

This leads to an error during deployment:

`Error: INSTALLATION FAILED: services "my-foundry-vtt" already exists`

![image](https://user-images.githubusercontent.com/38325136/163362215-e9a6ad92-7736-4b75-ad6e-3ef929791c3c.png)

The error is in the last three releases, I checked them 😄

**Comment by hugoprudente** [comment]
Great Catch, Thanks! I'm pushing the fixes. The repo is fixed, but the ArtifactoryHub artifact was faulty! Thanks!
