### ISSUE TITLE
Add Helm repo support

### ISSUE THREAD

**Issue by Sjoerdsjoerd** [hugoprudente/charts#50]
Add helm repo support, so that everyone can add the Helm repo without needing to check out the code.
See [link](https://tech.paulcz.net/blog/creating-a-helm-chart-monorepo-part-1) for an example implementation in GitHub.

**Comment by hugoprudente** [comment]
Hi @Sjoerdsjoerd it's already in the https://artifacthub.io/packages/helm/foundry-vtt/foundry-vtt

**Comment by Sjoerdsjoerd** [comment]
Thanks, that is exactly the thing I needed. 
Maybe it a good idea to add that in the Readme?

Thanks for the fast response 👍
